name: Enhancement
description: Make a specific, well-motivated proposal for a feature.
title: "[ENH]: ..."
labels: [enhancement]


body:
- type: markdown
  attributes:
    value: >
      Please post your idea first as a [Discussion](https://github.com/Akkudoktor-EOS/EOS/discussions)
      to validate it and bring attention to it. After validation,
      you can open this issue for a more technical developer discussion.
      Check the [Contributor Guide](https://github.com/Akkudoktor-EOS/EOS/blob/main/CONTRIBUTING.md)
      if you need more information.

- type: textarea
  attributes:
    label: "Link to discussion and related issues"
    description: >
      <link here>
    render: python
  validations:
    required: false

- type: textarea
  attributes:
    label: "Proposed implementation"
    description: >
      How it could be implemented with a high level API.
    render: python
  validations:
    required: false
