name: "Close stale pull requests/issues"
on:
  schedule:
  - cron: "16 00 * * *"

permissions:
  contents: read

jobs:
  stale:
    name: Find Stale issues and PRs
    runs-on: ubuntu-22.04
    if: github.repository == 'Akkudoktor-EOS/EOS'
    permissions:
      pull-requests: write # to comment on stale pull requests
      issues: write        # to comment on stale issues

    steps:
    - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
      with:
        stale-pr-message: 'This pull request has been marked as stale because it has been open (more
          than) 90 days with no activity. Remove the stale label or add a comment saying that you
          would like to have the label removed otherwise this pull request will automatically be
          closed in 30 days. Note, that you can always re-open a closed pull request at any time.'
        stale-issue-message: 'This issue has been marked as stale because it has been open (more
          than) 90 days with no activity. Remove the stale label or add a comment saying that you
          would like to have the label removed otherwise this issue will automatically be closed in
          30 days. Note, that you can always re-open a closed issue at any time.'
        days-before-stale: 90
        days-before-close: 30
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-pr-labels: 'in progress'
        exempt-issue-labels: 'feature request, enhancement'
        operations-per-run: 400
