CREATE TABLE IF NOT EXISTS eos_tail_plan (
  run_ts DATETIME NOT NULL,
  timestamp DATETIME NOT NULL,
  slot SMALLINT NOT NULL,
  action VARCHAR(32) NOT NULL,
  alternative_action VARCHAR(32) NULL,
  decision_margin_euro DOUBLE NULL,
  soc_start_pct DOUBLE NULL,
  soc_end_pct DOUBLE NULL,
  pv_wh DOUBLE NULL,
  load_wh DOUBLE NULL,
  grid_import_wh DOUBLE NULL,
  grid_export_wh DOUBLE NULL,
  battery_charge_wh DOUBLE NULL,
  battery_discharge_wh DOUBLE NULL,
  import_price_euro_kwh DOUBLE NULL,
  feed_in_tariff_euro_kwh DOUBLE NULL,
  slot_value_euro DOUBLE NULL,
  remaining_value_euro DOUBLE NULL,
  ac_charge_factor DOUBLE NULL,
  dc_charge_allowed TINYINT NULL,
  discharge_allowed TINYINT NULL,
  battery_grid_export_factor DOUBLE NULL,
  PRIMARY KEY (run_ts, slot),
  KEY ix_eos_tail_plan_timestamp (timestamp),
  KEY ix_eos_tail_plan_run (run_ts)
);
